name: Analyze code

on: push
  branches:
    - develop

jobs:
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.1'
          channel: 'stable'
          architecture: x64
      - name: Get dependencies
        run: flutter pub get
      # - name: Check Code Format
      #   run: dart format . --set-exit-if-changed
      # - name: Generate code
      #   run: dart run build_runner build
      - name: Analyze code
        run: dart analyze .